### ISSUE TITLE
freq_mask_path and space_mask_path

### ISSUE THREAD

**Issue by llllly26** [fudan-zvg/PDS#2]
Hi,
I want to know that,  If I want to use `freq_mask` and `space_mask` on my own datasets, how can I generate it? 
Thanks!

**Comment by AwakerMhy** [comment]
You can calculate the average value over the dataset for each pixel in each image to generate the space_mask, and calculate the average amptitude over the dataset of each frequency component in each image after Fourier transform for the freq_mask, as mentioned in Sec 4.3 of our paper.  Emprically, we find that about 200 images randomly sampled from the dataset is enough for calculating both masks.

**Comment by llllly26** [comment]
> You can calculate the average value over the dataset for each pixel in each image to generate the space_mask, and calculate the average amptitude over the dataset of each frequency component in each image after Fourier transform for the freq_mask, as mentioned in Sec 4.3 of our paper. Emprically, we find that about 200 images randomly sampled from the dataset is enough for calculating both masks.

thanks!
By the way, could you release code about this?  These parameters are necessary to generate high quality image, so I hope to keep align with your work.

**Comment by AwakerMhy** [comment]
Sure, I will add a demo about how to calculate the masks soon.

**Comment by AwakerMhy** [comment]
We have added the file [mask_gen_demo.py](https://github.com/fudan-zvg/PDS/blob/main/mask_gen_demo.py).py, which is a demo showing how to generate frequency and space mask for an image dataset. We take CIFAR10 as an example. We hope you find it helpful.

**Comment by llllly26** [comment]
> We have added the file [mask_gen_demo.py](https://github.com/fudan-zvg/PDS/blob/main/mask_gen_demo.py).py, which is a demo showing how to generate frequency and space mask for an image dataset. We take CIFAR10 as an example. We hope you find it helpful.

thanks!

**Comment by llllly26** [comment]
> We have added the file [mask_gen_demo.py](https://github.com/fudan-zvg/PDS/blob/main/mask_gen_demo.py).py, which is a demo showing how to generate frequency and space mask for an image dataset. We take CIFAR10 as an example. We hope you find it helpful.

 Sorry @AwakerMhy  , another confusion that, if different categories of images are different scale, need to [padding] and [mask] to same shape, but without using `torchvision.transforms` to `Resize`, in this scenario, does it make sense to calculate average?

**Comment by AwakerMhy** [comment]
For other datasets in which the raw images has different sizes, you need to resize them to have the same size and before calculating the masks.
